CREATE TABLE IF NOT EXISTS prompt_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1000),
    page_scope VARCHAR(32) NOT NULL,
    category VARCHAR(32),
    system_prompt TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    default_prompt BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_prompt_template_page_scope
    ON prompt_template (page_scope, active);

CREATE INDEX IF NOT EXISTS idx_prompt_template_category
    ON prompt_template (category, active);
