#!/usr/bin/env bash
set -e
export PGPASSWORD="${POSTGRES_PASSWORD:-nalbbun1234}"
DB_USER="${POSTGRES_USER:-nalbbun}"
TARGET_DB="nalbbun_api"
psql -v ON_ERROR_STOP=1 --username "$DB_USER" --dbname "$TARGET_DB" <<'SQL'
CREATE TABLE IF NOT EXISTS prompt_entry (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(32),
    system_prompt TEXT NOT NULL,
    description VARCHAR(500),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version_no INTEGER NOT NULL DEFAULT 1,
    previous_version_id VARCHAR(36),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_prompt_category ON prompt_entry (category);
CREATE INDEX IF NOT EXISTS idx_prompt_default ON prompt_entry (category, is_default);
CREATE TABLE IF NOT EXISTS prompt_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    page_scope VARCHAR(32) NOT NULL,
    category VARCHAR(32),
    system_prompt TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    default_prompt BOOLEAN NOT NULL DEFAULT FALSE,
    version_no INTEGER NOT NULL DEFAULT 1,
    previous_version_id BIGINT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_prompt_template_scope_category ON prompt_template(page_scope, category, active, default_prompt);
CREATE TABLE IF NOT EXISTS api_key_entry (
    id VARCHAR(36) NOT NULL PRIMARY KEY,
    provider VARCHAR(64) NOT NULL,
    label VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    key_value TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_api_key_provider ON api_key_entry (provider, active);
CREATE TABLE IF NOT EXISTS app_runtime_state (
    id BIGINT PRIMARY KEY,
    active_memory_store VARCHAR(32) NOT NULL,
    requested_memory_store VARCHAR(32) NOT NULL,
    restart_requested_at TIMESTAMP NULL,
    last_applied_at TIMESTAMP NULL,
    redis_session_ttl_minutes INTEGER NOT NULL DEFAULT 180,
    last_action VARCHAR(64) NULL
);
INSERT INTO app_runtime_state(id, active_memory_store, requested_memory_store, redis_session_ttl_minutes, last_action)
VALUES (1, 'in-memory', 'in-memory', 180, 'BOOTSTRAP')
ON CONFLICT (id) DO NOTHING;

ALTER TABLE app_runtime_state
    ADD COLUMN IF NOT EXISTS redis_memory_ttl_minutes INTEGER NOT NULL DEFAULT 1440;

CREATE TABLE IF NOT EXISTS prompt_entry_history (
    history_id BIGSERIAL PRIMARY KEY,
    prompt_id VARCHAR(36) NOT NULL,
    action VARCHAR(32) NOT NULL,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(32) NULL,
    system_prompt TEXT NOT NULL,
    description TEXT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version_no INTEGER NOT NULL DEFAULT 1,
    previous_version_id VARCHAR(36) NULL,
    captured_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_prompt_entry_history_prompt_id ON prompt_entry_history(prompt_id, captured_at DESC);

CREATE TABLE IF NOT EXISTS memory_snapshot (
    snapshot_id BIGSERIAL PRIMARY KEY,
    conversation_id VARCHAR(128) NOT NULL,
    label VARCHAR(255) NOT NULL,
    snapshot_json TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_memory_snapshot_conversation_id ON memory_snapshot(conversation_id, created_at DESC);
SQL
