#!/usr/bin/env bash
set -e
export PGPASSWORD="${POSTGRES_PASSWORD:-nalbbun1234}"
DB_USER="${POSTGRES_USER:-nalbbun}"
TARGET_DB="nalbbun_memory"
psql -v ON_ERROR_STOP=1 --username "$DB_USER" --dbname "$TARGET_DB" <<'SQL'
CREATE TABLE IF NOT EXISTS conversation_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(128) NOT NULL,
    role VARCHAR(32) NOT NULL,
    content TEXT NOT NULL,
    category VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS conversation_summary (
    conversation_id VARCHAR(128) NOT NULL,
    category VARCHAR(32) NOT NULL,
    summary TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY (conversation_id, category)
);
CREATE TABLE IF NOT EXISTS conversation_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(128) NOT NULL,
    category VARCHAR(32) NOT NULL,
    note TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_conversation_message_conversation_id ON conversation_message (conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_conversation_note_conversation_id ON conversation_note (conversation_id, created_at);
SQL
